
default: &default
  # adapter: sqlite3 変更
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode # 追加
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  # database: db/development.sqlite3 変更
  database: postgres

test:
  <<: *default
  # database: db/test.sqlite3 変更
  database: postgres

production:
  <<: *default
  # database: db/production.sqlite3 変更
  adapter: pg
  database: db/production.pg
  url: <%= ENV['DATABASE_URL'] %>